---
dist: xenial
language: python
python: "3.7"
sudo: required

services:
  - docker
install:
  - pip install pipenv
  - pipenv sync
script:
  - travis_wait 30 pipenv run molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
