---
- name: REDIS_EXPORTER | Setup container
  include: docker.yml
  tags:
    - install
  when: redis_exporter_dockerize

- name: REDIS_EXPORTER | Install
  include: install.yml
  tags:
    - install
  when: not redis_exporter_dockerize

- name: REDIS_EXPORTER | Configure
  include: config.yml
  tags:
    - configure
  when: not redis_exporter_dockerize

- name: REDIS_EXPORTER | Service
  include: service.yml
  tags:
    - service
  when: not redis_exporter_dockerize
